name: Run Tests on PR

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "apps/backend/**"
      - ".github/workflows/**"
      - ".github/templates/**"

jobs:
  find-tests:
    runs-on: ubuntu-latest
    outputs:
      test-batches: ${{ steps.find-tests.outputs.test-batches }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find test files
        id: find-tests
        uses: "./.github/templates/find-tests"
        with:
          batch-size: "3"

  test:
    needs: find-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-batch: ${{ fromJson(needs.find-tests.outputs.test-batches) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run test batch
        uses: "./.github/templates/test"
        with:
          test-batch: ${{ matrix.test-batch }}
