name: Deploy backend (prod)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/backend/**"
      - ".github/workflows/**"
      - ".github/templates/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: "./.github/templates/test"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: "./.github/templates/build-and-push"
        with:
          context: ./apps/backend
          file: ./apps/backend/Dockerfile
          dockerhub-username: ${{ secrets.BACKEND_DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.BACKEND_DOCKERHUB_TOKEN }}
          image-name: mcdominik/prismqr-backend-prod

      - name: Deploy
        uses: "./.github/templates/deploy-backend-container"
        with:
          host: ${{ secrets.BACKEND_PROD_SSH_HOST }}
          username: ${{ secrets.BACKEND_PROD_SSH_USER }}
          port: ${{ secrets.BACKEND_PROD_SSH_PORT }}
          ssh-private-key: ${{ secrets.BACKEND_PROD_SSH_KEY }}
          server-port: 3000
          application-port: 3000
          image-name: mcdominik/prismqr-backend-prod
          container-name: prismqr-backend-prod
          mongo-uri: ${{ secrets.BACKEND_PROD_MONGO_URI }}
          our-env: prod
          whitelisted-emails: ${{ secrets.BACKEND_PROD_WHITELISTED_EMAILS }}
          auth-jwt-secret: ${{ secrets.BACKEND_PROD_AUTH_JWT_SECRET }}
          admin-secret-admin-key: ${{ secrets.BACKEND_PROD_ADMIN_SECRET_ADMIN_KEY }}
          internal-telegram-bot-token: ${{ secrets.BACKEND_PROD_INTERNAL_TELEGRAM_BOT_TOKEN }}
          google-oauth-client-id: ${{ secrets.BACKEND_PROD_GOOGLE_OAUTH_CLIENT_ID }}
          google-oauth-client-secret: ${{ secrets.BACKEND_PROD_GOOGLE_OAUTH_CLIENT_SECRET }}

      - name: Prune
        uses: "./.github/templates/prune"
        with:
          host: ${{ secrets.BACKEND_PROD_SSH_HOST }}
          username: ${{ secrets.BACKEND_PROD_SSH_USER }}
          port: ${{ secrets.BACKEND_PROD_SSH_PORT }}
          ssh-private-key: ${{ secrets.BACKEND_PROD_SSH_KEY }}
